{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='v1', url='', help=''),
  applyConfiguration: (import 'applyConfiguration.libsonnet'),
  auditAnnotation: (import 'auditAnnotation.libsonnet'),
  expressionWarning: (import 'expressionWarning.libsonnet'),
  jsonPatch: (import 'jsonPatch.libsonnet'),
  matchCondition: (import 'matchCondition.libsonnet'),
  matchResources: (import 'matchResources.libsonnet'),
  mutatingAdmissionPolicy: (import 'mutatingAdmissionPolicy.libsonnet'),
  mutatingAdmissionPolicyBinding: (import 'mutatingAdmissionPolicyBinding.libsonnet'),
  mutatingAdmissionPolicyBindingSpec: (import 'mutatingAdmissionPolicyBindingSpec.libsonnet'),
  mutatingAdmissionPolicySpec: (import 'mutatingAdmissionPolicySpec.libsonnet'),
  mutatingWebhook: (import 'mutatingWebhook.libsonnet'),
  mutatingWebhookConfiguration: (import 'mutatingWebhookConfiguration.libsonnet'),
  mutation: (import 'mutation.libsonnet'),
  namedRuleWithOperations: (import 'namedRuleWithOperations.libsonnet'),
  paramKind: (import 'paramKind.libsonnet'),
  paramRef: (import 'paramRef.libsonnet'),
  ruleWithOperations: (import 'ruleWithOperations.libsonnet'),
  serviceReference: (import 'serviceReference.libsonnet'),
  typeChecking: (import 'typeChecking.libsonnet'),
  validatingAdmissionPolicy: (import 'validatingAdmissionPolicy.libsonnet'),
  validatingAdmissionPolicyBinding: (import 'validatingAdmissionPolicyBinding.libsonnet'),
  validatingAdmissionPolicyBindingSpec: (import 'validatingAdmissionPolicyBindingSpec.libsonnet'),
  validatingAdmissionPolicySpec: (import 'validatingAdmissionPolicySpec.libsonnet'),
  validatingAdmissionPolicyStatus: (import 'validatingAdmissionPolicyStatus.libsonnet'),
  validatingWebhook: (import 'validatingWebhook.libsonnet'),
  validatingWebhookConfiguration: (import 'validatingWebhookConfiguration.libsonnet'),
  validation: (import 'validation.libsonnet'),
  variable: (import 'variable.libsonnet'),
  webhookClientConfig: (import 'webhookClientConfig.libsonnet'),
}
