{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='v1alpha2', url='', help=''),
  basicSchedulingPolicy: (import 'basicSchedulingPolicy.libsonnet'),
  gangSchedulingPolicy: (import 'gangSchedulingPolicy.libsonnet'),
  podGroup: (import 'podGroup.libsonnet'),
  podGroupResourceClaim: (import 'podGroupResourceClaim.libsonnet'),
  podGroupResourceClaimStatus: (import 'podGroupResourceClaimStatus.libsonnet'),
  podGroupSchedulingConstraints: (import 'podGroupSchedulingConstraints.libsonnet'),
  podGroupSchedulingPolicy: (import 'podGroupSchedulingPolicy.libsonnet'),
  podGroupSpec: (import 'podGroupSpec.libsonnet'),
  podGroupStatus: (import 'podGroupStatus.libsonnet'),
  podGroupTemplate: (import 'podGroupTemplate.libsonnet'),
  podGroupTemplateReference: (import 'podGroupTemplateReference.libsonnet'),
  topologyConstraint: (import 'topologyConstraint.libsonnet'),
  typedLocalObjectReference: (import 'typedLocalObjectReference.libsonnet'),
  workload: (import 'workload.libsonnet'),
  workloadPodGroupTemplateReference: (import 'workloadPodGroupTemplateReference.libsonnet'),
  workloadSpec: (import 'workloadSpec.libsonnet'),
}
