{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='podGroupSpec', url='', help='"PodGroupSpec defines the desired state of a PodGroup."'),
  '#podGroupTemplateRef':: d.obj(help='"PodGroupTemplateReference references a PodGroup template defined in some object (e.g. Workload). Exactly one reference must be set."'),
  podGroupTemplateRef: {
    '#workload':: d.obj(help='"WorkloadPodGroupTemplateReference references the PodGroupTemplate within the Workload object."'),
    workload: {
      '#withPodGroupTemplateName':: d.fn(help='"PodGroupTemplateName defines the PodGroupTemplate name within the Workload object."', args=[d.arg(name='podGroupTemplateName', type=d.T.string)]),
      withPodGroupTemplateName(podGroupTemplateName): { podGroupTemplateRef+: { workload+: { podGroupTemplateName: podGroupTemplateName } } },
      '#withWorkloadName':: d.fn(help='"WorkloadName defines the name of the Workload object."', args=[d.arg(name='workloadName', type=d.T.string)]),
      withWorkloadName(workloadName): { podGroupTemplateRef+: { workload+: { workloadName: workloadName } } },
    },
  },
  '#schedulingConstraints':: d.obj(help='"PodGroupSchedulingConstraints defines scheduling constraints (e.g. topology) for a PodGroup."'),
  schedulingConstraints: {
    '#withTopology':: d.fn(help='"Topology defines the topology constraints for the pod group. Currently only a single topology constraint can be specified. This may change in the future."', args=[d.arg(name='topology', type=d.T.array)]),
    withTopology(topology): { schedulingConstraints+: { topology: if std.isArray(v=topology) then topology else [topology] } },
    '#withTopologyMixin':: d.fn(help='"Topology defines the topology constraints for the pod group. Currently only a single topology constraint can be specified. This may change in the future."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='topology', type=d.T.array)]),
    withTopologyMixin(topology): { schedulingConstraints+: { topology+: if std.isArray(v=topology) then topology else [topology] } },
  },
  '#schedulingPolicy':: d.obj(help='"PodGroupSchedulingPolicy defines the scheduling configuration for a PodGroup. Exactly one policy must be set."'),
  schedulingPolicy: {
    '#gang':: d.obj(help='"GangSchedulingPolicy defines the parameters for gang scheduling."'),
    gang: {
      '#withMinCount':: d.fn(help='"MinCount is the minimum number of pods that must be schedulable or scheduled at the same time for the scheduler to admit the entire group. It must be a positive integer."', args=[d.arg(name='minCount', type=d.T.integer)]),
      withMinCount(minCount): { schedulingPolicy+: { gang+: { minCount: minCount } } },
    },
    '#withBasic':: d.fn(help='"BasicSchedulingPolicy indicates that standard Kubernetes scheduling behavior should be used."', args=[d.arg(name='basic', type=d.T.object)]),
    withBasic(basic): { schedulingPolicy+: { basic: basic } },
    '#withBasicMixin':: d.fn(help='"BasicSchedulingPolicy indicates that standard Kubernetes scheduling behavior should be used."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='basic', type=d.T.object)]),
    withBasicMixin(basic): { schedulingPolicy+: { basic+: basic } },
  },
  '#withDisruptionMode':: d.fn(help='"DisruptionMode defines the mode in which a given PodGroup can be disrupted. Controllers are expected to fill this field by copying it from a PodGroupTemplate. One of Pod, PodGroup. Defaults to Pod if unset. This field is immutable. This field is available only when the WorkloadAwarePreemption feature gate is enabled."', args=[d.arg(name='disruptionMode', type=d.T.string)]),
  withDisruptionMode(disruptionMode): { disruptionMode: disruptionMode },
  '#withPriority':: d.fn(help='"Priority is the value of priority of this pod group. Various system components use this field to find the priority of the pod group. When Priority Admission Controller is enabled, it prevents users from setting this field. The admission controller populates this field from PriorityClassName. The higher the value, the higher the priority. This field is immutable. This field is available only when the WorkloadAwarePreemption feature gate is enabled."', args=[d.arg(name='priority', type=d.T.integer)]),
  withPriority(priority): { priority: priority },
  '#withPriorityClassName':: d.fn(help="\"PriorityClassName defines the priority that should be considered when scheduling this pod group. Controllers are expected to fill this field by copying it from a PodGroupTemplate. Otherwise, it is validated and resolved similarly to the PriorityClassName on PodGroupTemplate (i.e. if no priority class is specified, admission control can set this to the global default priority class if it exists. Otherwise, the pod group's priority will be zero). This field is immutable. This field is available only when the WorkloadAwarePreemption feature gate is enabled.\"", args=[d.arg(name='priorityClassName', type=d.T.string)]),
  withPriorityClassName(priorityClassName): { priorityClassName: priorityClassName },
  '#withResourceClaims':: d.fn(help="\"ResourceClaims defines which ResourceClaims may be shared among Pods in the group. Pods consume the devices allocated to a PodGroup's claim by defining a claim in its own Spec.ResourceClaims that matches the PodGroup's claim exactly. The claim must have the same name and refer to the same ResourceClaim or ResourceClaimTemplate.\\n\\nThis is an alpha-level field and requires that the DRAWorkloadResourceClaims feature gate is enabled.\\n\\nThis field is immutable.\"", args=[d.arg(name='resourceClaims', type=d.T.array)]),
  withResourceClaims(resourceClaims): { resourceClaims: if std.isArray(v=resourceClaims) then resourceClaims else [resourceClaims] },
  '#withResourceClaimsMixin':: d.fn(help="\"ResourceClaims defines which ResourceClaims may be shared among Pods in the group. Pods consume the devices allocated to a PodGroup's claim by defining a claim in its own Spec.ResourceClaims that matches the PodGroup's claim exactly. The claim must have the same name and refer to the same ResourceClaim or ResourceClaimTemplate.\\n\\nThis is an alpha-level field and requires that the DRAWorkloadResourceClaims feature gate is enabled.\\n\\nThis field is immutable.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='resourceClaims', type=d.T.array)]),
  withResourceClaimsMixin(resourceClaims): { resourceClaims+: if std.isArray(v=resourceClaims) then resourceClaims else [resourceClaims] },
  '#mixin': 'ignore',
  mixin: self,
}
