{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='podGroupTemplate', url='', help='"PodGroupTemplate represents a template for a set of pods with a scheduling policy."'),
  '#schedulingConstraints':: d.obj(help='"PodGroupSchedulingConstraints defines scheduling constraints (e.g. topology) for a PodGroup."'),
  schedulingConstraints: {
    '#withTopology':: d.fn(help='"Topology defines the topology constraints for the pod group. Currently only a single topology constraint can be specified. This may change in the future."', args=[d.arg(name='topology', type=d.T.array)]),
    withTopology(topology): { schedulingConstraints+: { topology: if std.isArray(v=topology) then topology else [topology] } },
    '#withTopologyMixin':: d.fn(help='"Topology defines the topology constraints for the pod group. Currently only a single topology constraint can be specified. This may change in the future."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='topology', type=d.T.array)]),
    withTopologyMixin(topology): { schedulingConstraints+: { topology+: if std.isArray(v=topology) then topology else [topology] } },
  },
  '#schedulingPolicy':: d.obj(help='"PodGroupSchedulingPolicy defines the scheduling configuration for a PodGroup. Exactly one policy must be set."'),
  schedulingPolicy: {
    '#gang':: d.obj(help='"GangSchedulingPolicy defines the parameters for gang scheduling."'),
    gang: {
      '#withMinCount':: d.fn(help='"MinCount is the minimum number of pods that must be schedulable or scheduled at the same time for the scheduler to admit the entire group. It must be a positive integer."', args=[d.arg(name='minCount', type=d.T.integer)]),
      withMinCount(minCount): { schedulingPolicy+: { gang+: { minCount: minCount } } },
    },
    '#withBasic':: d.fn(help='"BasicSchedulingPolicy indicates that standard Kubernetes scheduling behavior should be used."', args=[d.arg(name='basic', type=d.T.object)]),
    withBasic(basic): { schedulingPolicy+: { basic: basic } },
    '#withBasicMixin':: d.fn(help='"BasicSchedulingPolicy indicates that standard Kubernetes scheduling behavior should be used."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='basic', type=d.T.object)]),
    withBasicMixin(basic): { schedulingPolicy+: { basic+: basic } },
  },
  '#withDisruptionMode':: d.fn(help='"DisruptionMode defines the mode in which a given PodGroup can be disrupted. One of Pod, PodGroup. This field is available only when the WorkloadAwarePreemption feature gate is enabled."', args=[d.arg(name='disruptionMode', type=d.T.string)]),
  withDisruptionMode(disruptionMode): { disruptionMode: disruptionMode },
  '#withName':: d.fn(help='"Name is a unique identifier for the PodGroupTemplate within the Workload. It must be a DNS label. This field is immutable."', args=[d.arg(name='name', type=d.T.string)]),
  withName(name): { name: name },
  '#withPriority':: d.fn(help='"Priority is the value of priority of pod groups created from this template. Various system components use this field to find the priority of the pod group. When Priority Admission Controller is enabled, it prevents users from setting this field. The admission controller populates this field from PriorityClassName. The higher the value, the higher the priority. This field is available only when the WorkloadAwarePreemption feature gate is enabled."', args=[d.arg(name='priority', type=d.T.integer)]),
  withPriority(priority): { priority: priority },
  '#withPriorityClassName':: d.fn(help='"PriorityClassName indicates the priority that should be considered when scheduling a pod group created from this template. If no priority class is specified, admission control can set this to the global default priority class if it exists. Otherwise, pod groups created from this template will have the priority set to zero. This field is available only when the WorkloadAwarePreemption feature gate is enabled."', args=[d.arg(name='priorityClassName', type=d.T.string)]),
  withPriorityClassName(priorityClassName): { priorityClassName: priorityClassName },
  '#withResourceClaims':: d.fn(help="\"ResourceClaims defines which ResourceClaims may be shared among Pods in the group. Pods consume the devices allocated to a PodGroup's claim by defining a claim in its own Spec.ResourceClaims that matches the PodGroup's claim exactly. The claim must have the same name and refer to the same ResourceClaim or ResourceClaimTemplate.\\n\\nThis is an alpha-level field and requires that the DRAWorkloadResourceClaims feature gate is enabled.\\n\\nThis field is immutable.\"", args=[d.arg(name='resourceClaims', type=d.T.array)]),
  withResourceClaims(resourceClaims): { resourceClaims: if std.isArray(v=resourceClaims) then resourceClaims else [resourceClaims] },
  '#withResourceClaimsMixin':: d.fn(help="\"ResourceClaims defines which ResourceClaims may be shared among Pods in the group. Pods consume the devices allocated to a PodGroup's claim by defining a claim in its own Spec.ResourceClaims that matches the PodGroup's claim exactly. The claim must have the same name and refer to the same ResourceClaim or ResourceClaimTemplate.\\n\\nThis is an alpha-level field and requires that the DRAWorkloadResourceClaims feature gate is enabled.\\n\\nThis field is immutable.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='resourceClaims', type=d.T.array)]),
  withResourceClaimsMixin(resourceClaims): { resourceClaims+: if std.isArray(v=resourceClaims) then resourceClaims else [resourceClaims] },
  '#mixin': 'ignore',
  mixin: self,
}
