{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='podGroupStatus', url='', help='"PodGroupStatus represents information about the status of a pod group."'),
  '#withConditions':: d.fn(help="\"Conditions represent the latest observations of the PodGroup's state.\\n\\nKnown condition types: - \\\"PodGroupScheduled\\\": Indicates whether the scheduling requirement has been satisfied. - \\\"DisruptionTarget\\\": Indicates whether the PodGroup is about to be terminated\\n  due to disruption such as preemption.\\n\\nKnown reasons for the PodGroupScheduled condition: - \\\"Unschedulable\\\": The PodGroup cannot be scheduled due to resource constraints,\\n  affinity/anti-affinity rules, or insufficient capacity for the gang.\\n- \\\"SchedulerError\\\": The PodGroup cannot be scheduled due to some internal error\\n  that happened during scheduling, for example due to nodeAffinity parsing errors.\\n\\nKnown reasons for the DisruptionTarget condition: - \\\"PreemptionByScheduler\\\": The PodGroup was preempted by the scheduler to make room for\\n  higher-priority PodGroups or Pods.\"", args=[d.arg(name='conditions', type=d.T.array)]),
  withConditions(conditions): { conditions: if std.isArray(v=conditions) then conditions else [conditions] },
  '#withConditionsMixin':: d.fn(help="\"Conditions represent the latest observations of the PodGroup's state.\\n\\nKnown condition types: - \\\"PodGroupScheduled\\\": Indicates whether the scheduling requirement has been satisfied. - \\\"DisruptionTarget\\\": Indicates whether the PodGroup is about to be terminated\\n  due to disruption such as preemption.\\n\\nKnown reasons for the PodGroupScheduled condition: - \\\"Unschedulable\\\": The PodGroup cannot be scheduled due to resource constraints,\\n  affinity/anti-affinity rules, or insufficient capacity for the gang.\\n- \\\"SchedulerError\\\": The PodGroup cannot be scheduled due to some internal error\\n  that happened during scheduling, for example due to nodeAffinity parsing errors.\\n\\nKnown reasons for the DisruptionTarget condition: - \\\"PreemptionByScheduler\\\": The PodGroup was preempted by the scheduler to make room for\\n  higher-priority PodGroups or Pods.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='conditions', type=d.T.array)]),
  withConditionsMixin(conditions): { conditions+: if std.isArray(v=conditions) then conditions else [conditions] },
  '#withResourceClaimStatuses':: d.fn(help='"Status of resource claims."', args=[d.arg(name='resourceClaimStatuses', type=d.T.array)]),
  withResourceClaimStatuses(resourceClaimStatuses): { resourceClaimStatuses: if std.isArray(v=resourceClaimStatuses) then resourceClaimStatuses else [resourceClaimStatuses] },
  '#withResourceClaimStatusesMixin':: d.fn(help='"Status of resource claims."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='resourceClaimStatuses', type=d.T.array)]),
  withResourceClaimStatusesMixin(resourceClaimStatuses): { resourceClaimStatuses+: if std.isArray(v=resourceClaimStatuses) then resourceClaimStatuses else [resourceClaimStatuses] },
  '#mixin': 'ignore',
  mixin: self,
}
