{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='deviceAttribute', url='', help='"DeviceAttribute must have exactly one field set."'),
  '#withBool':: d.fn(help='"BoolValue is a true/false value."', args=[d.arg(name='bool', type=d.T.boolean)]),
  withBool(bool): { bool: bool },
  '#withBools':: d.fn(help='"BoolValues is a non-empty list of true/false values."', args=[d.arg(name='bools', type=d.T.array)]),
  withBools(bools): { bools: if std.isArray(v=bools) then bools else [bools] },
  '#withBoolsMixin':: d.fn(help='"BoolValues is a non-empty list of true/false values."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='bools', type=d.T.array)]),
  withBoolsMixin(bools): { bools+: if std.isArray(v=bools) then bools else [bools] },
  '#withInt':: d.fn(help='"IntValue is a number."', args=[d.arg(name='int', type=d.T.integer)]),
  withInt(int): { int: int },
  '#withInts':: d.fn(help='"IntValues is a non-empty list of numbers.\\n\\nThis is an alpha field and requires enabling the DRAListTypeAttributes feature gate."', args=[d.arg(name='ints', type=d.T.array)]),
  withInts(ints): { ints: if std.isArray(v=ints) then ints else [ints] },
  '#withIntsMixin':: d.fn(help='"IntValues is a non-empty list of numbers.\\n\\nThis is an alpha field and requires enabling the DRAListTypeAttributes feature gate."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ints', type=d.T.array)]),
  withIntsMixin(ints): { ints+: if std.isArray(v=ints) then ints else [ints] },
  '#withString':: d.fn(help='"StringValue is a string. Must not be longer than 64 characters."', args=[d.arg(name='string', type=d.T.string)]),
  withString(string): { string: string },
  '#withStrings':: d.fn(help='"StringValues is a non-empty list of strings. Each string must not be longer than 64 characters.\\n\\nThis is an alpha field and requires enabling the DRAListTypeAttributes feature gate."', args=[d.arg(name='strings', type=d.T.array)]),
  withStrings(strings): { strings: if std.isArray(v=strings) then strings else [strings] },
  '#withStringsMixin':: d.fn(help='"StringValues is a non-empty list of strings. Each string must not be longer than 64 characters.\\n\\nThis is an alpha field and requires enabling the DRAListTypeAttributes feature gate."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='strings', type=d.T.array)]),
  withStringsMixin(strings): { strings+: if std.isArray(v=strings) then strings else [strings] },
  '#withVersion':: d.fn(help='"VersionValue is a semantic version according to semver.org spec 2.0.0. Must not be longer than 64 characters."', args=[d.arg(name='version', type=d.T.string)]),
  withVersion(version): { version: version },
  '#withVersions':: d.fn(help='"VersionValues is a non-empty list of semantic versions according to semver.org spec 2.0.0. Each version string must not be longer than 64 characters.\\n\\nThis is an alpha field and requires enabling the DRAListTypeAttributes feature gate."', args=[d.arg(name='versions', type=d.T.array)]),
  withVersions(versions): { versions: if std.isArray(v=versions) then versions else [versions] },
  '#withVersionsMixin':: d.fn(help='"VersionValues is a non-empty list of semantic versions according to semver.org spec 2.0.0. Each version string must not be longer than 64 characters.\\n\\nThis is an alpha field and requires enabling the DRAListTypeAttributes feature gate."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='versions', type=d.T.array)]),
  withVersionsMixin(versions): { versions+: if std.isArray(v=versions) then versions else [versions] },
  '#mixin': 'ignore',
  mixin: self,
}
