{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='poolStatus', url='', help='"PoolStatus contains status information for a single resource pool."'),
  '#withAllocatedDevices':: d.fn(help='"AllocatedDevices is the number of devices currently allocated to claims. A value of 0 means no devices are allocated. May be unset when validationError is set."', args=[d.arg(name='allocatedDevices', type=d.T.integer)]),
  withAllocatedDevices(allocatedDevices): { allocatedDevices: allocatedDevices },
  '#withAvailableDevices':: d.fn(help='"AvailableDevices is the number of devices available for allocation. This equals TotalDevices - AllocatedDevices - UnavailableDevices. A value of 0 means no devices are currently available. May be unset when validationError is set."', args=[d.arg(name='availableDevices', type=d.T.integer)]),
  withAvailableDevices(availableDevices): { availableDevices: availableDevices },
  '#withDriver':: d.fn(help='"Driver is the DRA driver name for this pool. Must be a DNS subdomain (e.g., \\"gpu.example.com\\")."', args=[d.arg(name='driver', type=d.T.string)]),
  withDriver(driver): { driver: driver },
  '#withGeneration':: d.fn(help='"Generation is the pool generation observed across all ResourceSlices in this pool. Only the latest generation is reported. During a generation rollout, if not all slices at the latest generation have been published, the pool is included with a validationError and device counts unset."', args=[d.arg(name='generation', type=d.T.integer)]),
  withGeneration(generation): { generation: generation },
  '#withNodeName':: d.fn(help='"NodeName is the node this pool is associated with. When omitted, the pool is not associated with a specific node. Must be a valid DNS subdomain name (RFC1123)."', args=[d.arg(name='nodeName', type=d.T.string)]),
  withNodeName(nodeName): { nodeName: nodeName },
  '#withPoolName':: d.fn(help='"PoolName is the name of the pool. Must be a valid resource pool name (DNS subdomains separated by \\"/\\")."', args=[d.arg(name='poolName', type=d.T.string)]),
  withPoolName(poolName): { poolName: poolName },
  '#withResourceSliceCount':: d.fn(help='"ResourceSliceCount is the number of ResourceSlices that make up this pool. May be unset when validationError is set."', args=[d.arg(name='resourceSliceCount', type=d.T.integer)]),
  withResourceSliceCount(resourceSliceCount): { resourceSliceCount: resourceSliceCount },
  '#withTotalDevices':: d.fn(help='"TotalDevices is the total number of devices in the pool across all slices. A value of 0 means the pool has no devices. May be unset when validationError is set."', args=[d.arg(name='totalDevices', type=d.T.integer)]),
  withTotalDevices(totalDevices): { totalDevices: totalDevices },
  '#withUnavailableDevices':: d.fn(help='"UnavailableDevices is the number of devices that are not available due to taints or other conditions, but are not allocated. A value of 0 means all unallocated devices are available. May be unset when validationError is set."', args=[d.arg(name='unavailableDevices', type=d.T.integer)]),
  withUnavailableDevices(unavailableDevices): { unavailableDevices: unavailableDevices },
  '#withValidationError':: d.fn(help="\"ValidationError is set when the pool's data could not be fully validated (e.g., incomplete slice publication). When set, device count fields and ResourceSliceCount may be unset.\"", args=[d.arg(name='validationError', type=d.T.string)]),
  withValidationError(validationError): { validationError: validationError },
  '#mixin': 'ignore',
  mixin: self,
}
